[custom]

;设置规则标志位
ruleset=🛑 广告拦截,[]IP-CIDR,95.161.76.100/31
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,themoviedb.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,isafepal.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,mexc.co
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,bitgetapp.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,mobaibox.com
ruleset=🎯 全球直连,[]IP-CIDR,183.207.0.0/16
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,cctv.cn
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,yangshipin.cn
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,dnsany.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,cmvideo.cn
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,chinamobile.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,ottdns.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,02120913.xyz
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,150212.xyz
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,910321.xyz
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,5412838.xyz
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,spls.vip
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,zkt.icu
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,djniche1.eu.org
ruleset=🎬 公益服,https://raw.githubusercontent.com/qinguanlou/ACL4SSR/master/emby.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/bybit.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/binance.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/okx.list
;ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,googleapis.cn
ruleset=🚀 自建节点,[]DOMAIN-SUFFIX,googleapis.com
ruleset=🚀 自建节点,[]DOMAIN-SUFFIX,googleapis.cn
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,cloudflare.com
ruleset=♻️ OpenAI,[]DOMAIN-KEYWORD,openaicom
ruleset=♻️ OpenAI,[]DOMAIN-KEYWORD,chatgpt
ruleset=♻️ OpenAI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,torrentday.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,hdroute.org
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,pt.btschool.club
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,turgame.com
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,lemonhd.club
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,efflame.yachts
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,69shuba.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,nodeseek.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,v2rayssr.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,oracle.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,keeflys.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,subhd.tv
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,acgrip.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,masta.ee
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,nyaa.land
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hdhive.online
ruleset=🇭🇰 香港节点,[]DOMAIN-SUFFIX,u2.dmhy.org
ruleset=🇭🇰 香港节点,[]IP-CIDR,104.25.26.31/24
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,azusa.wiki
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,iptorrents.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,torrentleech.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,piggo.me
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,chdbits.co
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,ptchdbits.co
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hdchina.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,m-team.cc
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,ourbits.club
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,springsunday.net
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hdhome.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,tjupt.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hd4fans.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,keepfrds.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,pterclub.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hdarea.club
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,audiences.me
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hhanclub.top
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hhan.club
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,soulvoice.club
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,pttime.org
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,agsvpt.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,hdkyl.in
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,rousi.zip
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,icc2022.com
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,wintersakura.net
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,ptvicomo.net
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,xingyunge.top
ruleset=🔰 节点选择,[]DOMAIN-SUFFIX,cspt.top
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📲 GoogleVoice节点,[]DOMAIN,lens.l.google.com
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list
ruleset=📺 台湾流媒体,[]DOMAIN-SUFFIX,hinet.net
ruleset=📺 台湾流媒体,[]DOMAIN-SUFFIX,ofiii.com
ruleset=📺 台湾流媒体,[]DOMAIN-SUFFIX,4gtv.tv
ruleset=📺 台湾流媒体,[]DOMAIN-KEYWORD,myvideo
ruleset=📺 台湾流媒体,[]DOMAIN-KEYWORD,catchplay
ruleset=📺 台湾流媒体,[]DOMAIN-SUFFIX,akamaized.net
ruleset=📺 台湾流媒体,[]DOMAIN-KEYWORD,hamivideo
ruleset=📺 台湾流媒体,[]DOMAIN-KEYWORD,garageplay
ruleset=📺 台湾流媒体,[]DOMAIN-KEYWORD,kinostream
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
ruleset=🎬 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list
ruleset=🎥 Disney,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Disney.list
ruleset=🎥 亚马逊视频,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/AmazonPrimeVideo.list
ruleset=🎥 亚马逊视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=📺 ViuTV,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ViuTV.list
ruleset=🎥 HBO GO,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO_GO_HKG.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/qinguanlou/ACL4SSR/master/Clash/MyVideo.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/qinguanlou/ACL4SSR/master/Clash/CatchPLAY.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/friDay.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/qinguanlou/ACL4SSR/master/Clash/4gtv.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/VidolTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/LineTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/LiTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/KKTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TaiWanGood.list
ruleset=🎥 TVB,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/TVB.list
ruleset=🎶 Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BiliBili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🔰 节点选择`select`[]🚀 Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🚀 自建节点`[]🚀 赔钱`[]🚀 良心云`[]DIRECT
custom_proxy_group=🚀 手动切换`select`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`^((?!官网|订阅|域名|时间|流量|重置|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 Relay`select`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay
custom_proxy_group=🚀 赔钱`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(推荐|高速专线|晚高峰|下载|0.1x)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 良心云`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(CTCU|CMCU|CUCM|流媒体)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=📲 电报消息`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🚀 自建节点`[]🚀 赔钱`[]🚀 良心云
custom_proxy_group=♻️ OpenAI`select`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🚀 自建节点`[]🚀 赔钱`[]🚀 良心云`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(HKT|Akile|Hinet|RackNerd|Netcup|Buyvm)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 自建节点`select`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(amd|arm|RackNerd|Buyvm|Netcup|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎬 公益服`select`[]DIRECT`[]🚀 自建节点`[]🚀 赔钱`[]🚀 良心云`[]🚀 特殊节点`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点
custom_proxy_group=📹 油管视频`select`[]🔰 节点选择`[]🚀 Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎬 TikTok`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🔰 节点选择`[]🚀 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🔰 节点选择`[]🚀 手动切换`[]🚀 Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 特殊节点
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🔰 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📲 GoogleVoice节点`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(美国|States|USA)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🔰 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🔰 节点选择`[]🚀 手动切换`[]🚀 Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 特殊节点
custom_proxy_group=🚀 特殊节点`select`^((?!官网|订阅|域名|时间|流量|重置|套餐|Traffic|Expire|香港|日本|台湾|美国|新加坡|狮城|韩国).)*$
custom_proxy_group=🎶 Spotify`select`[]DIRECT`[]🚀 赔钱`[]🚀 良心云`[]🚀 特殊节点`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(菲律宾|amd|arm|RackNerd|Buyvm|Netcup|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
;custom_proxy_group=🎥 亚马逊视频`select`^((?!官网|订阅|域名|时间|流量|套餐|失联|Traffic|Expire).)*(香港|台湾|新加坡|狮城|日本|韩国|美国)((?!官网|订阅|域名|时间|流量|套餐|失联|Traffic|Expire).)*$
custom_proxy_group=🎥 亚马逊视频`select`[]🚀 赔钱`[]🚀 良心云`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(amd|arm|RackNerd|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎥 Disney`select`[]🚀 赔钱`[]🚀 良心云`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(amd|arm|RackNerd|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎥 TVB`select`[]🚀 赔钱`[]🚀 良心云`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(amd|arm|RackNerd|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎥 HBO GO`select`[]🚀 赔钱`[]🚀 良心云`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 狮城Relay`[]🚀 美国Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(马来西亚|菲律宾|amd|arm|RackNerd|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=📺 ViuTV`select`select`[]🚀 赔钱`[]🚀 良心云`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 狮城Relay`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(菲律宾|amd|arm|HKT|Akile|Hinet)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=📺 台湾流媒体`select`[]🚀 台湾Relay`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(台湾|Taiwan)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点1`[]🎥 奈飞节点2`[]🔰 节点选择`[]🚀 手动切换`[]🚀 特殊节点`[]🚀 赔钱`[]🚀 良心云
custom_proxy_group=🎥 奈飞节点1`select`[]🚀 香港Relay`[]🚀 台湾Relay`[]🚀 日本Relay`[]🚀 狮城Relay`[]🚀 美国Relay`^((?!官网|订阅|域名|时间|流量|套餐|失联|IEPL|Traffic|Expire).)*(amd|arm|GIA|RackNerd|aws|Buyvm|Netcup|HKT|Akile|Wap|Hinet)((?!官网|订阅|域名|时间|流量|套餐|失联|IEPL|Traffic|Expire).)*$
custom_proxy_group=🎥 奈飞节点2`select`^((?!IEPL|官网|订阅|域名|时间|流量|套餐|amd|arm|RackNerd|Buyvm|Netcup|HKT|Akile|Hinet|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*(香港|台湾|美国|狮城|日本|韩国)((?!IEPL|官网|订阅|域名|时间|流量|套餐|amd|arm|RackNerd|Buyvm|Netcup|HKT|Akile|Hinet|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*$
custom_proxy_group=🇭🇰 香港节点`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|Akile|HKT).)*(香港|Hong)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|Akile|Wap|HKT).)*$
custom_proxy_group=🇯🇵 日本节点`url-test`^((?!官网|订阅|域名|时间|流量|套餐|amd|arm|aws|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*(日本|Japan)((?!官网|订阅|域名|时间|流量|套餐|amd|arm|aws|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*$`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`^((?!官网|订阅|域名|时间|流量|套餐|RackNerd|amd|arm|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*(美国|States)((?!官网|订阅|域名|时间|流量|套餐|RackNerd|amd|arm|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*$`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`url-test`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|Akile|Hinet|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*(台湾|Taiwan)((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|Akile|Hinet|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*$`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`^((?!官网|订阅|域名|时间|流量|套餐|amd|arm|aws|Akile|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*(新加坡|狮城|Singapore)((?!官网|订阅|域名|时间|流量|套餐|amd|arm|aws|Akile|Traffic|Expire|推荐|高速专线|晚高峰|下载|0.1x|CTCU|CMCU|CUCM|流媒体).)*$`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`^((?!官网|订阅|域名|时间|流量|套餐|冷门|Traffic|Expire).)*(韩国|Korea)((?!官网|订阅|域名|时间|流量|套餐|冷门|Traffic|Expire).)*$`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 自建香港`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|台湾|新加坡).)*(HKT|Akile)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire|台湾|新加坡).)*$
custom_proxy_group=🚀 自建台湾`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire|香港|新加坡).)*(Akile|Hinet)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire|香港|新加坡).)*$
custom_proxy_group=🚀 自建日本`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(东京arm|大阪arm)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 自建狮城`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(新加坡amd|新加坡arm|新加坡西arm|新加坡Akile)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 自建美国`select`^((?!官网|订阅|域名|时间|流量|套餐|Traffic|Expire).)*(RackNerd|圣何塞arm|凤凰城arm)((?!官网|订阅|域名|时间|剩流量|套餐|Traffic|Expire).)*$
custom_proxy_group=🚀 香港Relay`relay`[]🇭🇰 香港节点`[]🚀 自建香港
custom_proxy_group=🚀 台湾Relay`relay`[]🇯🇵 日本节点`[]🚀 自建台湾
custom_proxy_group=🚀 日本Relay`relay`[]🇯🇵 日本节点`[]🚀 自建日本
custom_proxy_group=🚀 狮城Relay`relay`[]🇸🇬 狮城节点`[]🚀 自建狮城
custom_proxy_group=🚀 美国Relay`relay`[]🇺🇲 美国节点`[]🚀 自建美国
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
clash_rule_base=https://raw.githubusercontent.com/qinguanlou/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
